# docker-compose.yml
version: '3.8'
services:

  nginx:
    build:
      context: Nginx/
    deploy:
      replicas: 1
    labels:
      - traefik.http.routers.nginx.rule=Host(`nginx.localhost`)
      
  javalin:
    build:
      context: Javalin/
    deploy:
      replicas: 1
    labels:
      - traefik.http.routers.javalin.rule=Host(`javalin.localhost`)

  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true  # Enable Traefik dashboard
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80" # Web sites nginx and javalin
      - "8080:8080" # Traefik dashboard
